services:
  postgres:
    image: postgres:latest
    container_name: transaction-tracker
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/Projects/db-files/transaction-tracker

networks:
  app_network:
